name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.check_tag.outputs.new_version || steps.tag_version.outputs.new_version }}
      is_tag: ${{ steps.check_tag.outputs.is_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if this is a tag push
        id: check_tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "is_tag=true" >> $GITHUB_OUTPUT
            echo "new_version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "is_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Bump version and push tag
        id: tag_version
        if: steps.check_tag.outputs.is_tag == 'false'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch --tags
          VERSION=$(git tag --sort=-v:refname | head -n 1)
          if [ -z "$VERSION" ]; then
            VERSION="v0.0.0"
          fi
          NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF += 1 ; print}')
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          git tag $NEW_VERSION
          git push origin $NEW_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-amd64:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-amd64-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-amd64-
            ${{ runner.os }}-go-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/spray:${{ needs.tag.outputs.new_version }}-amd64
          build-args: |
            VERSION=${{ needs.tag.outputs.new_version }}
          cache-from: |
            type=gha,scope=amd64
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/spray:cache-amd64
          cache-to: |
            type=gha,mode=max,scope=amd64
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/spray:cache-amd64,mode=max

  build-arm64:
    needs: tag
    runs-on: ubuntu-24.04-arm  # Use native ARM64 runner (correct label)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-arm64-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-arm64-
            ${{ runner.os }}-go-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ARM64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/spray:${{ needs.tag.outputs.new_version }}-arm64
          build-args: |
            VERSION=${{ needs.tag.outputs.new_version }}
          cache-from: |
            type=gha,scope=arm64
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/spray:cache-arm64
          cache-to: |
            type=gha,mode=max,scope=arm64
            type=registry,ref=ghcr.io/${{ github.repository_owner }}/spray:cache-arm64,mode=max

  create-manifest:
    needs: [tag, build-amd64, build-arm64]
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-platform manifest
        run: |
          docker buildx imagetools create -t ghcr.io/${{ github.repository_owner }}/spray:${{ needs.tag.outputs.new_version }} \
            ghcr.io/${{ github.repository_owner }}/spray:${{ needs.tag.outputs.new_version }}-amd64 \
            ghcr.io/${{ github.repository_owner }}/spray:${{ needs.tag.outputs.new_version }}-arm64

      - name: Create and push latest manifest
        run: |
          docker buildx imagetools create -t ghcr.io/${{ github.repository_owner }}/spray:latest \
            ghcr.io/${{ github.repository_owner }}/spray:${{ needs.tag.outputs.new_version }}-amd64 \
            ghcr.io/${{ github.repository_owner }}/spray:${{ needs.tag.outputs.new_version }}-arm64

  create-release:
    needs: [tag, build-amd64, build-arm64, create-manifest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate release notes
        id: release_notes
        run: |
          # Get the previous tag
          PREV_TAG=$(git tag --sort=-v:refname | head -n 2 | tail -n 1)
          CURRENT_TAG=${{ needs.tag.outputs.new_version }}
          
          # Generate changelog
          echo "## What's Changed" > release_notes.md
          echo "" >> release_notes.md
          
          if [ ! -z "$PREV_TAG" ] && [ "$PREV_TAG" != "$CURRENT_TAG" ]; then
            echo "### Commits since $PREV_TAG:" >> release_notes.md
            git log --pretty=format:"- %s (%h)" ${PREV_TAG}..HEAD >> release_notes.md
          else
            echo "### Commits in this version:" >> release_notes.md  
            git log --pretty=format:"- %s (%h)" >> release_notes.md
          fi
          
          echo "" >> release_notes.md
          echo "## Docker Images" >> release_notes.md
          echo "" >> release_notes.md
          echo "### Multi-Platform (AMD64 + ARM64)" >> release_notes.md
          echo "\`\`\`bash" >> release_notes.md
          echo "docker pull ghcr.io/${{ github.repository_owner }}/spray:$CURRENT_TAG" >> release_notes.md
          echo "\`\`\`" >> release_notes.md
          echo "" >> release_notes.md
          echo "This release includes both AMD64 and ARM64 architectures." >> release_notes.md

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.tag.outputs.new_version }}
          release_name: Release ${{ needs.tag.outputs.new_version }}
          body_path: release_notes.md
          draft: false
          prerelease: false

