name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    paths-ignore:
      - '**'
      - '!.github/workflows/**'

jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Run Tests with Coverage
        id: test
        continue-on-error: true
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Convert coverage to lcov
        if: always()
        uses: jandelgado/gcov2lcov-action@v1.0.9
        with:
          infile: coverage.txt
          outfile: coverage.lcov

      - name: Send coverage to Coveralls
        if: always()
        uses: coverallsapp/github-action@v2
        with:
          file: coverage.lcov

      - name: Check test status
        if: steps.test.outcome == 'failure'
        run: exit 1

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Run Integration Tests
        id: integration_test
        run: go test -v -tags=integration ./...

      - name: Log Integration Test Status
        if: always()
        run: |
          if [ "${{ steps.integration_test.outcome }}" == "failure" ]; then
            echo "Integration tests failed (expected until GCP credentials are configured)"
          fi 